esphome:
  name: outdoor-lights-controller
  friendly_name: Outdoor Lights Controller

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "htNm+SneBJavNZNIUB3jzJLxwidHFJ1/LbigdcK4z4Y="

ota:
  - platform: esphome
    password: "9923d88d42bd1b50dc6ed9fa925e26ac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Outdoor-Lights-Controller"
    password: "aiLj0Y2idiYq"

switch:
  - platform: gpio
    name: "Power"
    pin: GPIO14
  
  - platform: gpio
    name: "Relay 1"
    pin: GPIO12

  - platform: gpio
    name: "Relay 2"
    pin: GPIO13

  - platform: gpio
    name: "Relay 3"
    pin: GPIO4

  - platform: gpio
    name: "Wifi LED"
    pin: GPIO2

  # - platform: gpio
  #   name: "Arduino LED"
  #   pin: GPIO14